import React from 'react';

interface UserAgreementModalProps {
  isOpen: boolean;
  onClose: () => void; // For viewer mode
  onAgree?: () => void; // For initial consent mode
  mode: 'initial' | 'viewer';
}

export const UserAgreementModal: React.FC<UserAgreementModalProps> = ({ isOpen, onClose, onAgree, mode }) => {
  if (!isOpen) return null;

  const handleContainerClick = (e: React.MouseEvent) => {
    // Only close if in viewer mode and clicking the backdrop
    if (mode === 'viewer') {
      onClose();
    }
  };

  const handleContentClick = (e: React.MouseEvent) => {
    e.stopPropagation();
  };

  return (
    <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4 animate-fade-in" onClick={handleContainerClick}>
      <div
        className="bg-[var(--bg-secondary)] rounded-xl border border-[var(--border-primary)] shadow-2xl w-full max-w-2xl flex flex-col h-auto max-h-[90vh]"
        onClick={handleContentClick}
      >
        <header className="flex-shrink-0 p-4 border-b border-[var(--border-primary)]">
          <h2 className="text-xl font-bold text-white">User Agreement & Terms of Service</h2>
        </header>

        <main className="flex-1 overflow-y-auto p-6 prose-custom prose-sm">
          <p>Last Updated: {new Date().toLocaleDateString()}</p>
          <h2>1. Introduction</h2>
          <p>Welcome to The Muse Engine ("the Application"). By accessing or using our Application, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree to these terms, please do not use the Application.</p>
          
          <h2>2. Use of the Service</h2>
          <p>The Muse Engine is a tool designed to assist with creative and technical exploration using the Google Gemini API. You agree to use the Application for lawful purposes only and in a manner that does not infringe the rights of, or restrict or inhibit the use and enjoyment of, this service by any third party.</p>
          
          <h2>3. User Accounts</h2>
          <p>When you create an account with us, you must provide information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service. You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.</p>

          <h2>4. Generated Content</h2>
          <p>The content generated by the AI ("Generated Content") is provided for informational and creative purposes only. While we strive to provide accurate information, we make no guarantees about the accuracy, reliability, or completeness of any Generated Content. You are responsible for any actions you take based on the information provided by the Application. You retain ownership of the prompts you provide, but you grant us a license to use them to operate and improve the service.</p>
          
          <h2>5. Disclaimers and Limitation of Liability</h2>
          <p>The Application is provided on an "AS IS" and "AS AVAILABLE" basis. We disclaim all warranties of any kind, whether express or implied. In no event shall The Muse Engine, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>

          <h2>6. Termination</h2>
          <p>We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
          
          <h2>7. Changes to Terms</h2>
          <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms of Service on this page. Your continued use of the Application after any such changes constitutes your acceptance of the new Terms of Service.</p>
        </main>
        
        <footer className="flex-shrink-0 p-4 border-t border-[var(--border-primary)] flex justify-end gap-3">
          {mode === 'initial' ? (
            <button
              onClick={onAgree}
              className="px-6 py-2 rounded-md bg-[var(--accent-primary)] hover:bg-[var(--accent-hover)] text-white font-semibold transition-colors"
            >
              I Understand and Agree
            </button>
          ) : (
             <button
              onClick={onClose}
              className="px-6 py-2 rounded-md bg-[var(--bg-tertiary)] hover:bg-[var(--border-primary)] text-white font-semibold transition-colors"
            >
              Close
            </button>
          )}
        </footer>
      </div>
    </div>
  );
};